### ISSUE TITLE
App quality regression. v2.4

### ISSUE THREAD

**Issue by ropucyka** [xdsopl/robot36#10] opened 2024-05-05 07:13 UTC
No autosave of received image.
Manual saving with artifacts (noise) and wrong size (empty space).
Bad image quality (compared to app version 1.45), and less settings in app.

Top image - from version 2.4, bottom image - from 1.45.

Used SSTV Encoder v2.10 by Olga. Phone - Samsung A30 (android 11).
Audio signal captured in identical conditions. Mode: Robot36

![20240505_115604](https://github.com/xdsopl/robot36/assets/22263977/a721216d-917b-4bc5-9f8a-fa442b674502)
-
![20240505_115905](https://github.com/xdsopl/robot36/assets/22263977/7ddd6b44-ae31-4a51-a0bb-30e0ca4f8ca6)

**Comment by xdsopl** [comment] 2024-05-05 07:31
Thank you for the feedback, I appreciate it.
There is automatic save since v2.3. Have you looked in your Pictures directory?
Also, the scaled scope images should not be compared for quality but the stored images in the Pictures directory.
Can you provide the audio file here so I can reproduce?
What settings are you missing? Have you tried a higher Sample Rate to improve the picture?
Thanks!

**Comment by ropucyka** [comment] 2024-05-05 08:01
> Have you looked in your Pictures directory?

Yes, it's not attached screenshots, but image files from gallery folder.
Bigger image - manualy saved (v2.4, because not autosaved), small - autosaved (v1.45)

> Have you tried a higher Sample Rate to improve the picture?

No information on user level about this "feature" in app. Both captured in 8 kHz SR.

> What settings are you missing?

Refresh rate, hide/show graph, image fit to screen size.
Cannot force set **Mode** to ignore all another modes when monitoring, or set **Auto** mode to accept all transmission modes - (Feature?)

Drop down menu a little lagging in animation.

> Can you provide the audio file here so I can reproduce?

[20240505_115458.zip](https://github.com/xdsopl/robot36/files/15212120/20240505_115458.zip)

**Comment by xdsopl** [comment] 2024-05-05 11:04
Just decoded these using an audio cable at a 8000, 16000, 32000, 44100 and 48000 Hz sample rate:
![8000 Hz](https://github.com/xdsopl/robot36/assets/1153394/e7ad91a5-f203-4bab-8bb6-4caace508b32)
![16000 Hz](https://github.com/xdsopl/robot36/assets/1153394/b7b578ab-d8f0-4a20-af39-2fc36d5b73c5)
![32000 Hz](https://github.com/xdsopl/robot36/assets/1153394/f4c2b178-456a-48a0-ac2b-dd66c0939827)
![44100 Hz](https://github.com/xdsopl/robot36/assets/1153394/a94856da-8b22-4bb4-b845-d1eb6d0e4229)
![48000 Hz](https://github.com/xdsopl/robot36/assets/1153394/c48d4358-cefe-468c-b8a7-0db4d2de7590)

**Comment by xdsopl** [comment] 2024-05-05 11:40
You are right that the 8000 Hz sample rate looks worst but I don't think that will be noticed when receiving over the air.
The higher the sample rate, the better the quality but also the higher the CPU usage, which means the battery drains faster.
I wanted to give the user the power to change those settings and use defaults that should work for most and also would not drain the battery too much.
This new rewrite of Robot36 does not use threads for the audio callback, which makes everything much, much simpler.
Unfortunately that might make the menu a bit sluggish but I think it is worth having a much simpler code and a higher chance for others to understand the code and eventually contribute.
Please also explain why you need the other settings.
The refresh rate already is at a very snappy 50 Hz.
Increasing it much further would use much more CPU power and lowering below 20 Hz would break the B/W decoding.
Do you really need the maximize scope and frequency plot toggle features?
Please understand that this rewrite of Robot36 is a last chance to save it on the the Android platform, as a lot has changed since it was initially released a decade ago.
So I need to keep it deliberately simple to cause me as little drain on motivation as possible to keep Robot36 alive, which means some sacrifices needed to be made.

**Comment by Xeddius** [comment] 2024-05-05 12:54
I like that you're working to improve the application, however I do believe removing the ability to manually set modes is a definitive mistake as automatic does not equate to better, sometimes I get transmissions with interference and the automatic mode doesn't decode the image at all while the old version does so long as the mode is set correctly.

Also when you already know the mode of the transmission you're trying to receive it makes sense to have the ability to set it manually, sometimes I don't want to decode the martin 2 signal that someone sent before I get the signal I am waiting for in Robot 24.

Having an update that suddenly removes features is not a good strategy as this will upset many users.
It may have been better to fork into a new application like Robot36-ng (next gen) so the old version can be preserved and users aren't updated to a version incompatible or unpleasant to use with their setup.

That being said, I am grateful this software is receiving some polish and I'm thankful that you're not abandoning it. Take your time, if you have to update it slowly that's perfectly okay, but please consider adding back the manual mode select.

**Comment by xdsopl** [comment] 2024-05-05 15:28
Not really trying to improve Robot36 .. the rewrite is necessary to avoid getting kicked out of the app store: The decoder is written in RenderScript, which is deprecated and a PITA to debug. The rest of the code is an unmaintainable mess and was written a decade ago on a platform that was much weaker in performance and what we have now is vastly different.

I have to admit, interference from other transmissions is a hard problem to solve and having an option to force the mode manually should be added to improve the situation. I did experiment with trying to ignore pulses from interferers but it made things much more complicated and as you just pointed out, the automatic mode might be decoding the interferer instead of the transmission you are waiting for. In that case a simpler decoder for a single mode that just offers manual phase and slant correction would be a better way.

**Comment by ropucyka** [comment] 2024-05-05 16:19
Old versions written with _RenderScript_ works well and have full classic functional, not glitching. I'll use them, while.
Looks like autosave worked several times, but with few seconds delay. Im absolutely sure that new version have problems with decoding but cannot say something exatly because not have technical knowns about it.

Using the application with one hand is very inconvenient, because you have to reach for the buttons at the top when working with one hand. and besides, because of this, the user constantly blocks his view with his hand.

Concept for you:
![2024-05-05_205827](https://github.com/xdsopl/robot36/assets/22263977/d322e40b-5a85-4882-ab1d-8a9c3457d77c)

I think you do not need to care about power usage, beacause its not battery saving app.
Do it powered!

And we still awaiting when you increase 5 KB (fk :-) image limit in COFDMTV apps.

**Comment by xdsopl** [comment] 2024-05-05 17:01
Okay, I will use the default audio settings from the current app: 44100 Hz sample rate and Microphone as input.
Changing (improving?) the graphical interface is not something I am looking forward to. Hopefully this will be done by contributors.
About COFDMTV: Yeah, I got sidetracked .. again .. this Robot36 business is costing me a month of development already.

**Comment by Xeddius** [comment] 2024-05-05 17:14
I definitely don't like to be of inconvenience, if I had the technical knowledge I'd implement the changes myself to assist.
Power usage isn't so much of an issue these days, and the UI is fine it only needs a little status bar, I really love the dark mode in the newest version.

**Comment by xdsopl** [comment] 2024-05-05 18:46
Use 44.1 kHz sample rate and microphone per default: commit 2ed8f985948ccc4259e063e7c10592bf283d39c3
Option to force mode: commit 1f67e185bc37d088cb1fff1e5854c93908e27c33

**Comment by xdsopl** [comment] 2024-05-06 07:40
Just released v2.5 here and on the app store as open beta.
Please test and report back any problems.

**Comment by ropucyka** [comment] 2024-05-06 11:13
**v2.5**
Looks like now images decoding normal, fully - from top to bottom.

1. When switching **Sample Rate** then selected **Force Mode** reseting to "**Robot 36 Color**".
2. If select **Auto**, app stiil showing previous selected **Force Mode** instead of **Auto** (it switching?).
3. Waterfall graph too small, narrow.

Autosave still not working at me.
So many empty space: app not showing current Sample Rate, Source, Audio Channel, Elapsed time for current decoding process, or something else, more.

Attached manualy saved image (just to be):
and yes, app saved it as upscaled (ass is). Robot 36 @ 48kHz

![20240506_154723](https://github.com/xdsopl/robot36/assets/22263977/47115c0e-7d21-4587-a757-2d461d08bfc7)

**Comment by xdsopl** [comment] 2024-05-06 13:08
> 1. When switching **Sample Rate** then selected **Force Mode** reseting to "**Robot 36 Color**".

Changing the Sample Rate creates a new decoder, resetting the decoder state. This is intentional.

> 2. If select **Auto**, app stiil showing previous selected **Force Mode** instead of **Auto** (it switching?).

It shows the last mode used while in free-run mode. This is intentional.

> 3. Waterfall graph too small, narrow.

Put the device in landscape mode if you want a larger frequency plot. Increasing the size of the frequency plot will make the image scope narrower, so the aspect-ratio can be kept. Maybe someone will contribute a toggle or some settings to change the size or the aspect-ratio in the future.

> Autosave still not working at me.

Can you please record the audio and put it here? From the image you provided it does not look like the calibration header was detected (no red or green horizontal bar). This usually means that the signal is too distorted, but the resulting picture looks okay ..

> So many empty space: app not showing current Sample Rate, Source, Audio Channel, Elapsed time for current decoding process, or something else, more.

The current audio settings can be seen in the menu: The chosen settings have a full and brighter dot. For the other things you mentioned, I hope others will contribute those features.

> Attached manualy saved image (just to be): and yes, app saved it as upscaled (ass is). Robot 36 @ 48kHz

The reason the picture is up-scaled is that we need to support modes with a lower and higher resolution: To have a correct aspect-ratio, we need to upscale the lower resolution modes in order to use the same scope for different modes.

**Comment by ropucyka** [comment] 2024-05-06 14:37
> Changing the Sample Rate creates a new decoder, resetting the decoder state. This is intentional.
> It shows the last mode used while in free-run mode. This is intentional.

Нет.
Если я выбрал режим "PD 90", то он не должен сбрасываться или переключаться на другой, какие бы настройки я не менял.
Если я выбрал режим "Martin 2" - должно показывать его, а если я выбрал "Auto" - должно показывать этот режим как текущий.

Я обнаружил что проблема с автосохранением связана с тем, что когда приложение свёрнуто, есть проблемы с получением заголовка, будто микрофон немного засыпает. Это и является причиной по которой автосохранение не работает. Думаю размещение иконки в области уведомлений могло бы решить этот вопрос (как в старых версиях), насколько я знаю, такой способ используют разработчики чтобы приложение оставалось активным даже в свёрнутом состоянии. Или это связано с разрешениями "Android", когда для микрофона указано разрешение "Разрешить только во время использования", другого наивысшего "Разрешить всегда" в этой версии "Android" нет.

Из моих наблюдений:
Когда приложение развёрнуто - оно успешно получает заголовок калибровки (зелёная полоса), и проблем с автосохранением нет.
Если приложение свёрнуто - заголовок калибровки и часть полезной нагрузки не обнаруживается, приложение считает полученные данные шумом и конечно не сохраняет результат передачи.

> The current audio settings can be seen in the menu: The chosen settings have a full and brighter dot. For the other things you mentioned, I hope others will contribute those features.

Посмотри. Ты единственный человек в этом мире кто работает над этим приложением для "SSTV" и над "Shredpix", "Assempix". Надеюсь вскоре ты закончишь работу над обновлением "Robot36" и возьмёшься за "Shredpix" и "Assempix". Многие очень ждут тебя там.

**Comment by xdsopl** [comment] 2024-05-06 18:44
Glad to see that we are on the same page. I will stop polishing Robot36 for now and continue working on my next COFDMTV project.

**Comment by xdsopl** [comment] 2024-05-07 07:04
I've added a toggle icon to switch between auto mode and to force mode to current mode: 1de7e40330bc15b5c40d94e350aff3fbf21b9b66

Also, the state is now preserved between sample rate changes.

I finally understood from your text why the calibration header detection seemed to fail:
By putting the app into background, for example to start the SSTV encoder, Robot36 stops recording.
Unfortunately, Google made it very clear, that recording while in background is a big no-no and also made it incredibly hard to get such a feature done right.
This is why I am not going to attempt to re-implement recording while in background.
We have the exact same problem with Assempix and Rattlegram: no recording in the background.
I am truly sorry about this, but I have to obey the rules if I want my apps to stay on the app stores.

**Comment by ropucyka** [comment] 2024-05-07 09:36
> I've added a toggle icon to switch between auto mode and to force mode to current mode: https://github.com/xdsopl/robot36/commit/1de7e40330bc15b5c40d94e350aff3fbf21b9b66

Good change but I am an advanced user with advanced knowledge, but not a programmer.
So me and many many anothers won’t be able to build the application based on this commit, or build (compile) anything.

Please, name apps according to their version and name, instead of "app-release.apk" otherwise, after downloading several of them, then it’s hard to understand where what is.

**Comment by xdsopl** [comment] 2024-05-07 09:52
I don't use my own apps, I have no idea what I'm doing and I'm not a programmer ..
You have to be patient for the next binary release.
Please report any problems with the current version, so I can integrate changes before the next binary release.
Thanks.

**Comment by ropucyka** [comment] 2024-05-07 09:57
> I don't use my own apps, I have no idea what I'm doing and I'm not a programmer

XD

Links in **About** tab is not clickable.

**Comment by ropucyka** [comment] 2024-05-07 10:08
In **Night** mode **Menu** and **Share** icons are gray but active, in **Light** mode all three icons are black and look normal.
As described above, and - 
I found that **Share** button is not active and are gray if nothing saved (its OK), but this button still gray even if we have saved image to share it. Same with **Light** mode - **Share** icon always looks like active.
Problem inverted for Night and Light modes.

Icons have different size.

Can move **Privacy Policy** information into **About** tab to make **Menu** more compact.

I think you can post test apk's here.

**Comment by xdsopl** [comment] 2024-05-07 12:52
The share and menu icons need to be fixed by Google. Playing with themes is no fun. They are always changing and breaking things. Do what I do: Don't look too close at the icons.

The Privacy Policy and About menu items are put exactly where Google wants me to put them: Very visible

Added clickable links and nicer text pages with commit: fbf8f51fdf98f0c8cdf3d6cc8e7734d30c28cdfd

**Comment by ropucyka** [comment] 2024-05-07 12:59
I have not see any another functional problems, at now.

Глупые правила и законы губят многие гениальные вещи.

**Comment by xdsopl** [comment] 2024-05-07 13:08
Don't think too much about the limitations .. think about what great things you can do inside those limitations.

v2.6 is released for testing. Please test and report back!

**Comment by ropucyka** [comment] 2024-05-07 14:50
> v2.6 is released for testing. Please test and report back!

I feel it works well.

![20240507_193114-1](https://github.com/xdsopl/robot36/assets/22263977/72c34b12-be6d-454b-9f3b-35a3f30f2239)

Not sure that text must be so close to window frame (at left side):
https://github.com/xdsopl/robot36/assets/22263977/23bc308d-2e16-48fd-852f-0a02b6c671d9
https://github.com/xdsopl/robot36/assets/22263977/e3f2667a-3d92-435e-8fbe-bb0a5e9a8a5b

Mode switch icon is cool, think its purpose is not intuitive enough to understand to new user (and old :-),
maybe need to use popup text like "Auto \ Lock Mode" when this icon pressed.

**Comment by xdsopl** [comment] 2024-05-07 16:11
> Not sure that text must be so close to window frame (at left side):

I know. Could not find a nice solution. Waiting for contributions for things like that.

> maybe need to use popup text like "Auto \ Lock Mode" when this icon pressed.

You need to long-press the icons.

**Comment by ropucyka** [comment] 2024-05-08 03:37
Why you sticked only with Google store with their rules?
You can do any features possible in your apps and publish it on F-Droid, here on GitHub, Huawei App Gallery.
And even i want to ask you to make developer account on https://dev.rustore.ru/en and publish your apps there, and i can help you with translation of app description to russian correctly to publish in store. Its main russian store which works as Google Play alternative, with goverment sponsoring and accesible worldwide.

> You need to long-press the icons.

Add ~1 second popup messages instead or another inform method.
Nobody knows about longtap because no information about it.

**Comment by xdsopl** [comment] 2024-05-08 04:34
> Why you sticked only with Google store with their rules?

Those are actually EU rules. There is no end to the micro-management and it gets 'better' every year.

> You can do any features possible in your apps and publish it on F-Droid, here on GitHub

I am very sure the other app stores will catch on soon when they face blocking and lawsuits.

Robot36 and Rattlegram are already on F-Droid, which was mostly done by the community. I like that. No extra work for me. Win-Win:

https://f-droid.org/en/packages/xdsopl.robot36/

https://apt.izzysoft.de/fdroid/index/apk/com.aicodix.rattlegram

You have no idea how many requests from countries all over the world I get for releasing my apps on their special platform. I just can't do that for free. I am simply not interested. I like the Math and the code. It also makes me happy to see others use my stuff to built upon their own projects and enjoy using it but beyond that, I simply do not care.

> Add ~1 second popup messages instead or another inform method.

No.

> Nobody knows about longtap because no information about it.

It's an Android feature. We have a mandatory driver's license for driving cars but not one for using computers. I hope this will change soon.

**Comment by xdsopl** [comment] 2024-05-08 07:39
> Not sure that text must be so close to window frame (at left side):

Added margins with commit 066e20065301b7a445da379c4ec67e4002c84ffd

> In Night mode Menu and Share icons are gray but active ..

Tried to improve the situation with commits 82d22525b943b07119ca39d307b6d45efa3f7cfb and ec67367dd3c5016bff23debccb6e5922951170e5

Made frequency plot look nicer in light mode with commit 0c690a156ec55d75d6454873762f1a3aae5826f3

Unless there is something that needs urgent fixing, I would like to start wrapping things up for the next binary release.

**Comment by ropucyka** [comment] 2024-05-08 08:19
> You have no idea how many requests from countries all over the world I get for releasing my apps on their special platform.

Its true?
___
A years ago found tool named as "SSTV image denoiser" on this page http://www.dxatlas.com/sstvtools/ Just note, nothing.

Add naming like "Robot36-v2.6.apk" instead "apk-release.apk". I downloaded more 12 times of your apk-release.apk an idk now where is what XD

**Comment by xdsopl** [comment] 2024-05-08 08:42
> > You have no idea how many requests from countries all over the world I get for releasing my apps on their special platform.
> 
> Its true?

There are literally hundreds of app stores world wide. Everyone wants a piece of the cake.

> A years ago found tool named as "SSTV image denoiser" on this page http://www.dxatlas.com/sstvtools/ Just note, nothing.

What are you trying to tell me? Image denoising is intriguing, yes, but so is forward error correction and digital image compression.
 
> Add naming like "Robot36-v2.6.apk" instead "apk-release.apk". I downloaded more 12 times of your apk-release.apk an idk now where is what XD

No.

**Comment by ropucyka** [comment] 2024-05-08 09:14
> No.

And reason?

It's time to close issue, app already true functional and even a bit polished, and i cannot help you here anymore. I see deeper about your apps and work than you can think.

**Comment by xdsopl** [comment] 2024-05-08 10:27
> > No.
> 
> And reason?

Because.

> It's time to close issue, app already true functional and even a bit polished, and i cannot help you here anymore

Of course you can still help and I very much appreciate your feedback: Just released v2.7. Please test and report back.

**Comment by ropucyka** [comment] 2024-05-08 10:43
![2024-05-08_152952](https://github.com/xdsopl/robot36/assets/22263977/2ce7588b-d14d-4472-bc3d-068efbbdab12)

**Comment by ropucyka** [comment] 2024-05-08 12:34
PD 290 mode is missing in Force Mode list

Martin modes must have M1 M2 names, not 1 2. Same with Scottie modes, S1 S2

**Comment by xdsopl** [comment] 2024-05-08 12:41
> PD 290 mode is missing in Force Mode list

I removed it from the supported modes, because it is the only mode that uses a horizontal resolution larger than 640 pixels. This way we can easily upscale 320 pixel to 640 by simple pixel duplication to keep the aspect ratio. Do you think removing PD290 was a mistake?

> Martin modes must have M1 M2 names, not 1 2

I used the naming convention from the Dayton Paper:

http://www.barberdsp.com/downloads/Dayton%20Paper.pdf

**Comment by ropucyka** [comment] 2024-05-08 12:58
idk. in old, long 170 pages handbook from Martin Bruchanov it have modes names, not numbers
You just removed different mode
![108 05 2024_54](https://github.com/xdsopl/robot36/assets/22263977/86204e7b-ff48-452a-881f-1074a68a2cfc)
![108 05 2024_55](https://github.com/xdsopl/robot36/assets/22263977/102e1acb-4c99-4bb0-919a-96f4c8bc44c4)

**Comment by xdsopl** [comment] 2024-05-08 13:03
I trust the data in the Dayton Paper more. There are actually specifications of the modes in there. The SSTV handbook is a joke in that regard.

**Comment by xdsopl** [comment] 2024-05-15 12:13
It's a week since last testing release and I did not get any bad feedback since then. So I am promoting this release to production. I did some more visual improvements, but they will be held back until next release. I am closing this now and would like to thank everyone for their invaluable feedback and participation in improving Robot36. Until next time!

**Closed as completed by xdsopl** 2024-05-15 12:13 UTC
